server:
  port: 5555
  
spring:
  application:
    name: API-Gate

  cloud:
    gateway:
      routes:
        - id: auth-service-app
          uri: lb://AUTHSERVICEAPP
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}
        
        - id: propertyservice-api
          uri: lb://PROPERTYSERVICE
          predicates:
            - Path=/property/**
          filters:
            - RewritePath=/property/(?<segment>.*), /${segment}